### ISSUE TITLE
Allow custom font size

### ISSUE THREAD

**Issue by el-analista** [aws/mynah-ui#75]
## Problem
Currently font size is not customizable which makes appearance to be bigger than the rest when actually as this being an extension we would like to have smaller font size
<img width="852" alt="image" src="https://github.com/user-attachments/assets/99e5f372-622c-4ef8-8e10-5b86d04d215a">

As it can be seen prompt font size is way bigger than main code window, suggestions is the tiniest and response is same as code window(would like to have smaller)

**Comment by dogusata** [comment]
MynahUI does allow custom font sizes. See [theming documentation](https://github.com/aws/mynah-ui/blob/main/docs/STYLING.md)

Adding 
```css
:root {
    font-size: ??px/rem/em...;
}
```
to the place MynahUI consumed is sufficient.  MynahUI adjusts the text size depending on the root font-size. So even without touching the mynahui's custom properties it is possible to adjust the size.
