### ISSUE TITLE
Empty chat box remained after user selection

### ISSUE THREAD

**Issue by tincheng** [aws/mynah-ui#77]
## Problem

Amazon Q Code Transform uses the Button feature `keepCardAfterClick = false`, which was previously working. The last version where it should have been working was around @4.9.2, which was updated in this [PR](https://github.com/aws/aws-toolkit-jetbrains/commit/c056cd4281491c33c0505e37837883b179af4383).

Here are how the buttons were configured in [aws/aws-toolkit-jetbrain](https://github.com/aws/aws-toolkit-jetbrains/blob/30e721e1e77fec80fb6d19ef05a158261944ac83/plugins/amazonq/codetransform/jetbrains-community/src/software/aws/toolkits/jetbrains/services/codemodernizer/constants/CodeTransformChatItems.kt#L37-L49).

Tested with latest **@aws/mynah-ui@4.15.2** (verified with `npm list @aws/mynah-ui`)

https://github.com/user-attachments/assets/7a505092-63e1-4b4e-ba09-d5537879058b

## Steps to reproduce the issue

1. Type `/transform` in Amazon Q Chat to kickoff transformation
2. In the chat box for Q - Code transformation, click with Cancel or Confirm. 
3. Observe the issue.

## Expected behavior

The chat box should disappear completely. No empty small chat box should remain.

## System details

- OS: Mac
- Tested enviroment:
    - [ ] Web (Demo app)
    - [ ] VSCode Amazon Q Chat
    - [x] JetBrains IntelliJ Amazon Q Chat
- Enviroment extension version (if applicable):
- [ ] Enviroment is remote

**Comment by dogusata** [comment]
Seems like issue is already solved with previous remaining card issues:

https://github.com/user-attachments/assets/6c17dea6-8f1c-484e-8f8c-c8bedd4850e7

https://github.com/aws/mynah-ui/releases/tag/v4.14.0
