### ISSUE TITLE
Adding a scroll bar in Q chat

### ISSUE THREAD

**Issue by manodnyab** [aws/mynah-ui#81]
## Description
While the scrolling functionality exists in Q chat panel, can we also add a visual component aka scroll bar to indicate the position in the chat panel?

**Comment by 32teeth** [comment]
This one should be trivial

this is why there is no scroll bar
```
    ::-webkit-scrollbar {
        width: 2px;
        height: 2px;
        opacity: 0.25;
        &:horizontal {
            width: 0px;
            height: 0px;
        }
    }    
```
