### ISSUE TITLE
VsCode tab scrollbar shrinks height of tabs

### ISSUE THREAD

**Issue by akhamis-amzn** [aws/mynah-ui#90]
## Problem

When creating lots of tabs, the height of the tabs shrinks, making it look very odd

How it looks normally:
<img width="624" alt="Screenshot 2024-08-07 at 10 31 31 AM" src="https://github.com/user-attachments/assets/32494b58-3c29-4582-8cc8-e4fe34bd9be4">

Once scrollbar appears:
<img width="591" alt="Screenshot 2024-08-07 at 10 31 25 AM" src="https://github.com/user-attachments/assets/f0500e10-d3f2-4971-8da7-b6c128f00a8e">

## Steps to reproduce the issue

Create a bunch of tabs, observe how the scrollbar is display

## Expected behavior

Height of the tabs does not shrink

## System details

- OS: Mac
- Tested enviroment:
    - [ ] Web (Demo app)
    - [X] VSCode Amazon Q Chat
    - [ ] JetBrains IntelliJ Amazon Q Chat
- Enviroment extension version (if applicable): 
- [ ] Enviroment is remote

**Comment by dogusata** [comment]
PR is live.
